### ISSUE TITLE
Add cancel example to README

### ISSUE THREAD

**Issue by guergabo** [resonatehq/resonate#100]
Include cancel example in the README.md. Perhaps bring in the downstream, upstream language that the specification's README.md has. 

```
r.POST("/promises/:id/cancel", s.cancelPromise)
r.POST("/promises/:id/create", s.createPromise)
r.POST("/promises/:id/resolve", s.resolvePromise)
r.POST("/promises/:id/reject", s.rejectPromise)
```

**Comment by khanh130202** [comment]
i can add readme.md

**Comment by guergabo** [comment]
Awesome! Thanks @khanh130202 for your interest in contributing. 

If anything else stands out or is not clear enough in the README, pls also feel free to suggest any other enhancements. 

With regard, to the "downstream, upstream" language I mentioned above, I was referring to this README: https://github.com/resonatehq/durable-promise/tree/main

**Comment by KannappanChida** [comment]
@guergabo I'm interested to work on this, can i work on this documentation update

**Comment by guergabo** [comment]
@KannappanChida. yes, pls ! reach out if you need any help.

**Comment by guergabo** [comment]
this issue is now stale after the readme update for v0.1.0.
