### ISSUE TITLE
Should be able to just list all promises

### ISSUE THREAD

**Issue by guergabo** [resonatehq/resonate#101]
We shouldn't always require a query for listing promises. An end user first trying out the server might just want to see all promises they just created and should do so as simply as possible with very little friction. I propose we offer a default pagination behavior where we don't enforce the user to provide query parameters for pagination if the number of total promises is under the max page size. 

<img width="608" alt="Screenshot 2023-11-04 at 11 11 03 PM" src="https://github.com/resonatehq/resonate/assets/65991626/84634246-d4de-492d-8626-7b8cf298db05">

**Comment by pancholinaman07** [comment]
HI I would like to contribute but didnt know where to started as for my spec i have intermediate background in golang and postgrel

**Comment by guergabo** [comment]
Hi! thanks for your interest in contributing to Resonate! 

After some thought i actually think this would be great for usability, but opens the server to being attacked and/or performance issues. I will close for now and ask that you look at the other issues that were recently created and comment on one of those. 

If i can help in any way please reach out. thanks again for your interest!
