### ISSUE TITLE
No matches found for search api 

### ISSUE THREAD

**Issue by guergabo** [resonatehq/resonate#102]
According to the [durable promise spec](https://github.com/resonatehq/durable-promise/blob/main/spec/durable-promise.yaml), this should be a valid query, but returns no matches. Yet, a get request does show there is a match. 

<img width="1505" alt="Screenshot 2023-11-05 at 10 31 31 PM" src="https://github.com/resonatehq/resonate/assets/65991626/57e2ba85-de1c-44f6-8ae4-f7e504513d82">

This issue covers debugging and validating that all four query parameters work properly: 
- q
- state
- limit
- cursor. 

Additionally, we should have documentation surrounding how it works.

Additionally, q alone should not be required, but rather I propose that at least 1 of the 4 is required. Open to other ideas and suggestions!

**Comment by KannappanChida** [comment]
@guergabo , I'm interested in contributing to this, can i work on this issue

**Comment by guergabo** [comment]
Yes, of course! Thanks for your interest @KannappanChida . 👏

Please feel free to reach out or comment if you have any follow-up questions.

**Comment by guergabo** [comment]
fyi the no matches found was partially an error from my part `curl "http://localhost:8001/promises?q=*`... needs quotes surrounding the url 💀. 

We should still do ?q=* by default in order to enable 

 `curl "http://localhost:8001/promises?state=resolved` as a valid search query since q is required and we need good documentation on this.

**Comment by guergabo** [comment]
this is already handled here: https://github.com/resonatehq/resonate/pull/111
