### ISSUE TITLE
Why `slog` was chosen as the Logging Library in the project

### ISSUE THREAD

**Issue by dreamjz** [resonatehq/resonate#114]
Sorry to bother you. I should have asked this question in issue #94 but forgot >_<.

I am a beginner contributing to an open-source Golang project; perhaps this is a dumb question.

I have a question about why `slog` was chosen as the logging library instead of `zap` or `zerolog`. 
They have better performance as indicated by benchmark data in their documentation and they provide more log-level options.

**Comment by dfarr** [comment]
We evaluated a few different options including zap. One of the guiding principles of this project is to minimize dependencies, we chose slog is because it is part of the go standard library.

**Comment by dreamjz** [comment]
Thank you for your response.😊
