### ISSUE TITLE
Design Discussion • Resonate Schedules

### ISSUE THREAD

**Issue by dtornow** [resonatehq/resonate#132]
### Feature

**tl;dr**

The Resonate Server should be able to schedule **the creation of promises**

**Description**

Many applications require the ability to schedule **tasks**. In the context of the Resonate Server, a task is represented by a **Durable Promise**. Therefore, **scheduling of a task** is the **creation of a promise**. Subsequently, the Resonate Server facilitates the completion of a promise (see #133)

See #139 for Resonate Timers

**Comment by guergabo** [comment]
### Design Proposal 

In terms of data structures to holds, [this research paper](https://paulcavallaro.com/blog/hashed-and-hierarchical-timing-wheels/) is very popular in the space of timer systems and looks at all our options: 

1. Unordered List 
2. Sorted List 
3. Priority Queues 
4. Timed Wheels

**Comment by guergabo** [comment]
Already completed.
