### ISSUE TITLE
Collapse the Resolve, Reject, Cancel Coroutines to 1 Complete Coroutine

### ISSUE THREAD

**Issue by guergabo** [resonatehq/resonate#166]
It really only is 1 type of operation. same logic.

**Comment by favalos** [comment]
Can you elaborate more on this? No difference in the response?

**Comment by guergabo** [comment]
Hi @favalos, sorry for the ambiguity. What I meant is the following: 

1. Recently, we did a refactor to our promise API and the resolve, reject, and cancel promise operations are all behind a PATCH (http) or COMPLETE (grpc) api endpoint. Look here: https://github.com/resonatehq/resonate/blob/main/internal/app/subsystems/api/http/promise.go#L105
2. If you see we are switching and choosing one of the three operations, but if you follow down the path of "completing a promise", the business logic is exactly the same minus the actual "state transition" (pending to resolve, reject, or cancel).
3. Therefore, we can get rid of the copy paste resolve, reject and cancel coroutines and just have one "completePromise" coroutine that handles any state transition from pending to "resolve, reject, or cancel" to limit the boilerplate and similar logic.

Hope this makes sense. If you are interested, this would be a great issue to get an understanding of our system. LMK if you have any follow-up questions.

**Comment by favalos** [comment]
Hey @guergabo,

I am working on this, I am very interested in learning more about resonate. Will let you know if I have questions.

Thanks!

**Comment by guergabo** [comment]
Awesome to hear, @favalos ! Looking forward to your questions and PR 🔥

**Comment by favalos** [comment]
Thanks!

**Comment by dfarr** [comment]
Thank _you_ @favalos !!!
