### ISSUE TITLE
Limit schedules queried in schedule promises coroutine

### ISSUE THREAD

**Issue by dfarr** [resonatehq/resonate#169]
Currently our query looks like
```sql
SELECT
  id, description, cron, promise_id, promise_param_headers, promise_param_data, promise_timeout, last_run_time, next_run_time, created_on, idempotency_key
FROM
  schedules
WHERE
  next_run_time <= ?
```

We should place an ORDER BY and LIMIT on this query. LIMIT will ensure we don't overload our system, and an ORDER BY can ensure that the next batch will pick up where the previous one left off. Additionally, I think we can remove some columns from this query.

We can expose the limit value in the [system configuration](https://github.com/resonatehq/resonate/blob/main/cmd/serve/serve.go#L224-L227).

**Comment by aneessh18** [comment]
this issue can be closed.
