### ISSUE TITLE
reduce false negatives in github actions

### ISSUE THREAD

**Issue by guergabo** [resonatehq/resonate#181]
## Describe the problem you are facing 
We've been getting a long of false negatives and dst issues created. This is because it will either have trouble downloading the resonate binary or the logs to compare. This results in a failure and an issue is created. 

## Describe the solution you'd like
Move some of this logic into a script to add retries and timeouts. Improve the logic so it only creates issue for actual failures. 

## Alternatives you've considered
Perhaps there are github actions that can help with this.

**Comment by dfarr** [comment]
Additionally: include link to github action run in the github issue

**Comment by dfarr** [comment]
I'm going to close this issue for now, hopefully using cache vs artifacts for the resonate binary will cut down on false negatives a bit
