### ISSUE TITLE
Return successful response (200) when strict=false and state=REJECTED_TIMEDOUT

### ISSUE THREAD

**Issue by dfarr** [resonatehq/resonate#206]
When a promise times out we can no longer deduplicate using the completed idempotency key as the server sets this key as opposed to the client (and in fact the server sets the key to nil in the case of a timeout).

Instead of matching the complete idempotency key on the {resolve, reject, cancel} requests, let's only match the key iff **state is not REJECTED_TIMEDOUT**.

Coroutines affected:
- resolvePromise
- rejectPromise
- cancelPromise

Note: the response should still be unsuccessful (403) if strict=true.

Additionally we will need to update the state transition table appropriately and regenerate the sdk store tests. See resonatehq/resonate-sdk-ts#24

**Comment by favalos** [comment]
Can you assign this to me please?

**Comment by guergabo** [comment]
love the energy, @favalos !

**Comment by dfarr** [comment]
Thank you so much @favalos! I will take care of this today
> Additionally we will need to update the state transition table appropriately and regenerate the sdk store tests. See https://github.com/resonatehq/resonate-sdk-ts/issues/24
