### ISSUE TITLE
Resonate Quickstart

### ISSUE THREAD

**Issue by dtornow** [resonatehq/resonate#240]
The resonate CLI should include a **Quickstart Command** to create a minimal getting started app for the specified sdk

```
$ resonate quickstart [sdk]
```

The command outputs getting started instructions, for example, for typescript:

```
$ resonate quickstart ts

Getting started with Resonate for TypeScript

> 🏴‍☠️ 1. Run git clone git@github.com:resonatehq/ts-quickstart.git quickstart && cd quickstart
> 🏴‍☠️ 2. Follow the Getting Started instructions in Readme.md
```

In essence, the Quickstart Command prints but does not execute the necessary steps for a user to run to get started

**Comment by vaibhawvipul** [comment]
https://github.com/resonatehq/resonate/pull/244 - for review
