### ISSUE TITLE
[DST] Monitors & Announcements

### ISSUE THREAD

**Issue by dtornow** [resonatehq/resonate#247]
## Describe the solution you'd like

Monitor Partitioning & Announcement Routing

## Additional context

- https://p-org.github.io/P/manual/monitors/
- https://p-org.github.io/P/manual/statements/?h=announce#raise

## Question

- Algorithm

**Comment by vaibhawvipul** [comment]
more information is here  - [issue 268](https://github.com/resonatehq/resonate/issues/268)
