### ISSUE TITLE
Assertion on SQE/CQE Callback

### ISSUE THREAD

**Issue by dtornow** [resonatehq/resonate#266]
# Problem

During our recent experimentation with the DST, it became apparent that our system is susceptible to invariant violations which currently go undetected

I believe there are two invariants invariants in the system:

1. **SQE** At the point of enqueueing, every Submission Queue Entry (SQE) must have an associated callback set.
2. **CQE** At the point of dequeuing, every Completion Queue Entry (CQE) must have an associated callback set.

# Proposed Solution

To address this issue, I propose the integration of two assertions within the scheduler

1. For the SQE Invariant: Insert an assertion to verify that a callback is set for each SQE before it is enqueued.
2. For the CQE Invariant: Insert an assertion to ensure that a callback is set for each CQE after it is dequeued.

# Conclusion and Call to Action

Ensuring our system's invariants is crucial for maintaining correctness. By encoding these invariants as assertions, we take a proactive step towards ensuring correctness. This practice should be extended to encompass more system invariants, further embedding the principle of fail-fast and ensuring that any violations are promptly identified and addressed.

I invite feedback on this proposal and encourage a discussion on identifying additional invariants that could benefit from similar enforcement mechanisms.

**Comment by guergabo** [comment]
it appears as if the sqe callback is already enforced and set by the scheduler: https://github.com/resonatehq/resonate/blob/4c1b89c625828ba72787c0abe84c55bd77d26a98/internal/kernel/scheduler/scheduler.go#L52 

We can still assert the cqe callback a few lines above.

**Comment by guergabo** [comment]
we can also do something like this where we set it before calling enqueue:  

`
sqe := &bus.SQE[t_aio.Submission, t_aio.Completion]{}
util.Assert(sqe.callback != nil)
s.aio.Enqueue(sqe)
`

**Comment by aneessh18** [comment]
> we can also do something like this where we set it before calling enqueue:
> 
> `sqe := &bus.SQE[t_aio.Submission, t_aio.Completion]{} util.Assert(sqe.callback != nil) s.aio.Enqueue(sqe)`

can we close this issue ?
