### ISSUE TITLE
Logging & Metrics

### ISSUE THREAD

**Issue by dfarr** [resonatehq/resonate#3]
# Logging

Structured logs - [slog](https://go.dev/blog/slog) - are now a part of the go standard library. Let's use this over third party options (eg. zap).

# Metrics

Let's use prometheus for metrics and prefer cross cutting metrics wherever possible. Initially let's implement counters, specifically:
- IO Operations
  - type
  - total/success/failure
- Coroutines
  - total
  - in progress
- API
  - type (http/grpc)
  - total/success/failure (500s + 429)

**Comment by dtornow** [comment]
Let's add a docs/metrics.md document detailing the metrics and their dimensions as we add them
