### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by dtornow** [resonatehq/resonate#330]
## Describe the problem you are facing 

Currently, the Resonate Server does not support authentication and authorization

## Describe the solution you'd like

Add Basic Auth for authentication for the Resonate's http api

## Additional context

This is a first step towards a mature authentication and authorization system. The design of the authentication and authorization system will be discussed in a separate issue

**Comment by dtornow** [comment]
Resonate uses the [gin web framework](https://gin-gonic.com) so we can use the gin Basic Auth middleware. The (list of) user can be configured via the configuration file or command line arguments. E.g.

```
// Apply Basic Auth middleware conditionally
    authorized := r.Group("/")
    // username password pairs could also be a list to configure multiple accounts
    if config.AuthUsername != "" && config.AuthPassword != "" {
        accounts := gin.Accounts{
            config.AuthUsername: config.AuthPassword,
        }
        basicAuthMiddleware := gin.BasicAuth(accounts)
        authorized.Use(basicAuthMiddleware)
    }

    // Promises API
    authorized.POST("/promises", s.createPromise)
    authorized.GET("/promises", s.searchPromises)
    authorized.GET("/promises/*id", s.readPromise)
    authorized.PATCH("/promises/*id", s.completePromise)
    
    // ...
```

See [source file](https://github.com/resonatehq/resonate/blob/9f31bbeea4951acf642553fae4a533b7c1ab2624/internal/app/subsystems/api/http/http.go#L28)

In subsequent iterations, we need to design how to attach authenticated user information to our api requests.

**Comment by dtornow** [comment]
**Additional information**

- Every API endpoint is registered on the authorized group

- `Config` needs to be extended to contain `AuthUsername` and `AuthPassword` (if we only care about single user) or a list of Username Password pairs (if we want to support multiple users)

- Username and password can be configured via config file or via cobra command line arguments

**Comment by RyanCarlisle** [comment]
Hi, is this issue already assigned to someone?

**Comment by hkiiita** [comment]
@dtornow requesting your review on https://github.com/resonatehq/resonate/pull/333
