### ISSUE TITLE
Routing subsystem

### ISSUE THREAD

**Issue by dfarr** [resonatehq/resonate#385]
Matchers are registered on an instance of the resonate server and apply to promises. When a promise created matchers are tested in order, the first matcher to signal a match triggers the creation of a task.

Matchers can be used to _invoke_ processes, in contrast to callbacks which are generally used to _resume_ processes.

**Comment by flossypurse** [comment]
Changed name from "matchers" to "routers".
"Routers" accept a promise and return a destination.
