### ISSUE TITLE
Add task cli commands

### ISSUE THREAD

**Issue by dfarr** [resonatehq/resonate#436]
Claim, complete, and heartbeat tasks.

Commands:
- claim
- complete
- heartbeat

Examples:
```
resonate tasks claim --id foo --counter 1 --process-id bar --ttl 1m
resonate tasks complete --id foo --counter 1
resonate tasks heartbeat --id foo --counter 1
```

See [promises](https://github.com/resonatehq/resonate/tree/main/cmd/promises) and [schedules](https://github.com/resonatehq/resonate/tree/main/cmd/schedules) for a reference.

**Comment by TusharMohapatra07** [comment]
Hello, does this issue needs any prerequisite knowledge of cloud ?

**Comment by dfarr** [comment]
> Hello, does this issue needs any prerequisite knowledge of cloud ?

Not at all! This is just request/response from client to server.

**Comment by TusharMohapatra07** [comment]
Okay then, i'd like to work on this.

**Comment by dfarr** [comment]
Thank you @TusharMohapatra07 !!!

**Comment by dfarr** [comment]
Completed by #443
