### ISSUE TITLE
Alternate storage backends: MySQL and etcd-io/BBolt

### ISSUE THREAD

**Issue by huesflash** [resonatehq/resonate#89]
Can and should resonate support MySql and BBolt (kv) storage backends ?

Apologies if this isn’t the right place to pose such questions. I’d be interested in implementing them.

**Comment by dfarr** [comment]
Alternate storages are definitely on the roadmap, including supporting key-value stores. Just out of curiosity, what would be the benefits for you of mysql over postgres?

**Comment by huesflash** [comment]
Just for coverage and I know MySQL has many fans :/
As for the KV, I like what restatedev is doing with their distributed workers that also act as stores for latency and durability reasons. Is a similar design being considered for resonate ?

**Comment by dfarr** [comment]
That's a really good question, @huesflash do you mind joining our [community slack](http://resonatehq.io/slack) and we can talk more in depth? We are currently in the process of deciding and prioritizing features.

**Comment by guergabo** [comment]
I agree with you @huesflash on MySQL. It would be a great addition given its popularity. 

dropping this to show anyone interested in contributing and helping us out where in the codebase we store our db implementations: 

- https://github.com/resonatehq/resonate/tree/53d377535e2dbe7f8e05915c092c65513c33ccab/internal/app/subsystems/aio/store. 

Thanks!

**Comment by Madraceee** [comment]
Hey, Can I work on this?
If this is still open that. I can go through the code and then give my commitment if thats okay with you guys.

**Comment by dfarr** [comment]
Closing as won't do for the time being
