### ISSUE TITLE
Improve log level flag description 

### ISSUE THREAD

**Issue by guergabo** [resonatehq/resonate#94]
Currently, the default log level for the `resonate serve` command does not output any incoming requests. Therefore, I imagine the `--log-level` flag will be used quite a bit by the end users. The description is not clear enough what options we offer. 

<img width="511" alt="Screenshot 2023-11-04 at 6 11 33 PM" src="https://github.com/resonatehq/resonate/assets/65991626/c27becd5-c7c6-49e4-890c-78e8f586f4ea">

**Comment by dfarr** [comment]
We are using slog for structured go logs, the level is an [integer type](https://pkg.go.dev/golang.org/x/exp/slog#Level). I think it makes a lot of sense to map a string to its corresponding level
```
DEBUG -> -4
INFO  -> 0
WARN  -> 4
ERROR -> 8
```
