### ISSUE TITLE
Do not return resource for anything other than 2xxs

### ISSUE THREAD

**Issue by guergabo** [resonatehq/resonate#96]
The below image shows that if i DO NOT use an idempotency key and yet try to create the same object twice i get back the same promise. It looks idempotent on the CLI. The server does return different status codes for both calls 201 and then 403. But, this should be an error message. 

Also, I believe 409 makes more sense for this type of error since its more of a resource conflict than a forbidden request. 

![screenshot_2023-11-03_at_1 41 11_pm](https://github.com/resonatehq/resonate/assets/65991626/ba2ffa2f-86bb-46ff-8603-18de1da0dcee)

**Comment by guergabo** [comment]
this also applies to 403s which are when trying to complete a promise after its already been completed. (without idempotency key again).

**Comment by dfarr** [comment]
I think adding the `omitempty` json tag to the necessary go structs will get us most of the way there. For 403s we will need to additionally null out the promise.
