### ISSUE TITLE
Create fresh db every time

### ISSUE THREAD

**Issue by guergabo** [resonatehq/resonate#97]
Currently, if we run `resonate serve` it creates a `resonate.db` file. Every time I rerun the server it DOES NOT create a new `resonate.db`, but rather uses the old one implicitly. 

It is not explicit that, by default, the db lives beyond the lifecycle of the server. This could lead to confusion and end users getting unexpected test results. 

We want a fresh db every time the server is started. Let's either delete the db, and/or startup the server with a new filename.

**Comment by dfarr** [comment]
For durability we need the database to survive application restarts, this should be the default behaviour. We can provide an optional flag to reset the db on shutdown, there already is a lifecycle hook in the code called `Reset` that implements the logic to do this.

**Comment by pancholinaman07** [comment]
For fresh db every time we can just add the query to delete database if already exist

**Comment by favalos** [comment]
Looking forward to do this change.

Should we add a flag for SQLLite to Reset?

BTW, can I get the link to join Slack?

**Comment by guergabo** [comment]
@favalos yea i think a flag would be a nice approach. i'll try to get to this soon, but feel free to submit a PR. as @dfarr mentioned, there is  Reset() function that already implements this logic, just need to trigger it conditionally based on whether or not the flag has been set. 

slack is on the readme, but here you go: https://resonatehqcommunity.slack.com/
