### ISSUE TITLE
Do not implicitly set timeout to 0

### ISSUE THREAD

**Issue by guergabo** [resonatehq/resonate#98]
If the end user does not set the timeout, then there should just not be any timeout. Currently, if an end user does not set a timeout it implicitly sets it to 0 and the promise immediately goes into a `REJECTED_TIMEDOUT` state.  

<img width="1512" alt="Screenshot 2023-11-04 at 6 29 12 PM" src="https://github.com/resonatehq/resonate/assets/65991626/dff343bc-ede6-4c16-a910-7d7b46e88db3">

**Comment by guergabo** [comment]
make it a part of the configuration file. the first thing they see. comment and suggest end users "you need to set a timeout". default is 300 seconds for usability (for now).

**Comment by guergabo** [comment]
another alternative for this is to just make the timeout required so its always an explicit action. this would require updating the spec.

**Comment by dfarr** [comment]
If we make the timeout required, what if we require it on the "global" Resonate object rather than each individual durable promise for convenience?
